#!/usr/bin/env bash

for ((i=0;i<$1;++i)); do
    which_punk=$(printf '%04d' $i)
    curl https://www.larvalabs.com/public/images/cryptopunks/punk$which_punk.png -o ~/Pictures/NFTs/cryptopunk$i.png
done
